### ISSUE TITLE
Entries missing from Patchouli book

### ISSUE THREAD

**Issue by Ryminer2** [gamma-delta/HexMod#147]
Playing on the Direwolf20 1.18 modpack. 

Hexcasting version: 0.9.0
Patchouli version: 1.18.2-71
PAUCAL version: 0.4.7
Forge version: 40.1.52

Opened up my world from before the 0.9.0 update and all of the categories in the Patchouli book are present, but all of the _entries_ in them are missing, except for the Getting Started chapter. Issue persists in new worlds, even after eating the Media Cube in creative mode.

![image](https://user-images.githubusercontent.com/6020841/175391560-57fc7387-79bd-448e-9079-7b37538a845b.png)

**Comment by gamma-delta** [comment]
Can you post your logs, please?

This might be a Patchouli issue.

**Comment by Ryminer2** [comment]
[latest.log](https://github.com/gamma-delta/HexMod/files/8970781/latest.log)

Log does seem to indicate Patchouli problems, but all other books that are accessible ingame work as normal.

**Comment by poboy975** [comment]
Hello, I'm also following the direwolf letsplay and I'm having the same issue as well. Also when I entered a geode after crafting the book, I didn't get the achievement automatically. No charged dust so far either. I used a command to grant the /root achievement, but it didn't unlock the rest of the entries. 

Here is my log.
[latest.log](https://github.com/gamma-delta/HexMod/files/8973159/latest.log)

**Comment by KirinDave** [comment]
So the relevant issue seems to be: 

`java.lang.RuntimeException: Entry in file hexcasting:patchouli_books/thehexbook/en_us/entries/interop/interop.json does not have a valid category.`

Which is weird because looking in the book, I see a valid category and it was added before the 0.9 release.

Someone came into the discord tonight asking about the same issue.

**Comment by KirinDave** [comment]
Just to follow up, I opened a fresh world with the latest version of Direwolf's modpack and I don't see this. Nor do I see this with a fresh world in All the Mods or the Ars Nouveau serverpack.

**Comment by poboy975** [comment]
I haven't tried a fresh world. I started the modpack about 2-3 weeks ago. I know there have been at least 2 updates to the modpack in the ftb launcher since I started. Maybe something is carrying over from an older version and interfering somehow.

**Comment by williewillus** [comment]
Patchouli 1.18.2-71 had a bug leading to entries not loading properly in some cases. Try with 1.18.2-71.1 which I just released.

**Comment by poboy975** [comment]
I'll update it this evening after work and update you. Thanks

**Comment by poboy975** [comment]
After updating last night, everything worked. The book filled in the rest of the entries. Thanks!

**Comment by fafilon** [comment]
does anyone know when the bug of pages not being displayed will be fixed. is the author going to fix it? yf dthcbb 1.18.2. Version 71.1 didn't fix anything (((

**Comment by object-Object** [comment]
we are probably not going to release any more updates for 1.18.2. you can read the book online here: https://hexcasting.hexxy.media/v/0.9.6/1.0/en_us/
